apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cacher
spec:
  selector:
    matchLabels:
      app: redis-cacher
  serviceName: "redis-cacher"
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-cacher
    spec:
      containers:
      - name: redis
        image: "redis:6.2.6"
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
          - "--cluster-announce-ip"
          - "$(IPADDR)"
        ports:
          - name: redis-client
            containerPort: 6379
            protocol: "TCP"
          - name: redis-peer-node
            containerPort: 16379
            protocol: "TCP"
        volumeMounts:
          - name: "redis-conf"
            mountPath: "/etc/redis"
          - name: "redis-data"
            mountPath: "/var/lib/redis/data"
        env:
        - name: IPADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: "redis-conf"
        configMap:
          name: "redis-cacher"
          items:
            - key: "redis.conf"
              path: "redis.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
